# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(630, 550)
        mainWindow.setMinimumSize(QtCore.QSize(630, 550))
        mainWindow.setMaximumSize(QtCore.QSize(630, 480))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushbutton_opensource = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_opensource.setGeometry(QtCore.QRect(10, 10, 131, 30))
        self.pushbutton_opensource.setObjectName("pushbutton_opensource")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(140, 10, 441, 30))
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_file_name = QtWidgets.QLabel(self.centralwidget)
        self.label_file_name.setGeometry(QtCore.QRect(210, 50, 250, 16))
        self.label_file_name.setText("")
        self.label_file_name.setObjectName("label_file_name")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 70, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_file_size = QtWidgets.QLabel(self.centralwidget)
        self.label_file_size.setGeometry(QtCore.QRect(210, 70, 250, 16))
        self.label_file_size.setText("")
        self.label_file_size.setObjectName("label_file_size")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 90, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_file_duration = QtWidgets.QLabel(self.centralwidget)
        self.label_file_duration.setGeometry(QtCore.QRect(210, 90, 250, 16))
        self.label_file_duration.setText("")
        self.label_file_duration.setObjectName("label_file_duration")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 110, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_file_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_file_resolution.setGeometry(QtCore.QRect(210, 110, 250, 16))
        self.label_file_resolution.setText("")
        self.label_file_resolution.setObjectName("label_file_resolution")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 130, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_file_frame_rate = QtWidgets.QLabel(self.centralwidget)
        self.label_file_frame_rate.setGeometry(QtCore.QRect(210, 130, 250, 16))
        self.label_file_frame_rate.setText("")
        self.label_file_frame_rate.setObjectName("label_file_frame_rate")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(130, 180, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(295, 180, 21, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.checkbox_aspect_ratio = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_aspect_ratio.setGeometry(QtCore.QRect(390, 180, 181, 20))
        self.checkbox_aspect_ratio.setObjectName("checkbox_aspect_ratio")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 210, 60, 16))
        self.label_11.setObjectName("label_11")
        self.radiobutton_cbr = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton_cbr.setGeometry(QtCore.QRect(230, 210, 61, 20))
        self.radiobutton_cbr.setObjectName("radiobutton_cbr")
        self.radiobutton_vbr = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton_vbr.setGeometry(QtCore.QRect(230, 240, 61, 20))
        self.radiobutton_vbr.setObjectName("radiobutton_vbr")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 210, 61, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(290, 240, 111, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 240, 31, 20))
        self.label_14.setObjectName("label_14")
        self.pushButton_start_transcoding = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_transcoding.setGeometry(QtCore.QRect(460, 350, 141, 32))
        self.pushButton_start_transcoding.setObjectName("pushButton_start_transcoding")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 380, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushbutton_browse_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_browse_file.setGeometry(QtCore.QRect(160, 379, 91, 31))
        self.pushbutton_browse_file.setObjectName("pushbutton_browse_file")
        self.label_path_dash = QtWidgets.QLabel(self.centralwidget)
        self.label_path_dash.setGeometry(QtCore.QRect(170, 410, 441, 51))
        self.label_path_dash.setText("")
        self.label_path_dash.setWordWrap(True)
        self.label_path_dash.setObjectName("label_path_dash")
        self.pushButton_start_generating_DASH_MPD = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_generating_DASH_MPD.setGeometry(QtCore.QRect(400, 490, 201, 32))
        self.pushButton_start_generating_DASH_MPD.setObjectName("pushButton_start_generating_DASH_MPD")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(100, 150, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_file_bit_rate = QtWidgets.QLabel(self.centralwidget)
        self.label_file_bit_rate.setGeometry(QtCore.QRect(210, 150, 250, 16))
        self.label_file_bit_rate.setText("")
        self.label_file_bit_rate.setObjectName("label_file_bit_rate")
        self.radiobutton_abr = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton_abr.setGeometry(QtCore.QRect(230, 270, 61, 20))
        self.radiobutton_abr.setObjectName("radiobutton_abr")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(360, 270, 131, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_width = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_width.setGeometry(QtCore.QRect(230, 180, 61, 21))
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.lineEdit_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_height.setGeometry(QtCore.QRect(320, 180, 61, 21))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.lineEdit_cbr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cbr.setGeometry(QtCore.QRect(290, 210, 61, 21))
        self.lineEdit_cbr.setObjectName("lineEdit_cbr")
        self.lineEdit_vbr_max = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vbr_max.setGeometry(QtCore.QRect(410, 240, 61, 21))
        self.lineEdit_vbr_max.setText("")
        self.lineEdit_vbr_max.setObjectName("lineEdit_vbr_max")
        self.lineEdit_abr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_abr.setGeometry(QtCore.QRect(290, 270, 61, 21))
        self.lineEdit_abr.setText("")
        self.lineEdit_abr.setObjectName("lineEdit_abr")
        self.lineEdit_segment_duration = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_segment_duration.setGeometry(QtCore.QRect(440, 300, 61, 21))
        self.lineEdit_segment_duration.setObjectName("lineEdit_segment_duration")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(510, 300, 61, 20))
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(130, 300, 111, 16))
        self.label_19.setObjectName("label_19")
        self.checkBox_custom_segment_duration = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_custom_segment_duration.setGeometry(QtCore.QRect(250, 300, 201, 20))
        self.checkBox_custom_segment_duration.setObjectName("checkBox_custom_segment_duration")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 330, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_saved_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_saved_name.setGeometry(QtCore.QRect(430, 330, 161, 21))
        self.lineEdit_saved_name.setObjectName("lineEdit_saved_name")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(440, 470, 31, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_dash_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dash_title.setGeometry(QtCore.QRect(480, 470, 113, 21))
        self.lineEdit_dash_title.setObjectName("lineEdit_dash_title")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.pushbutton_opensource.setText(_translate("mainWindow", "Open Source File"))
        self.label.setText(_translate("mainWindow", "Summary:"))
        self.label_3.setText(_translate("mainWindow", "Name"))
        self.label_5.setText(_translate("mainWindow", "Size"))
        self.label_4.setText(_translate("mainWindow", "Duration"))
        self.label_6.setText(_translate("mainWindow", "Transcoding:"))
        self.label_7.setText(_translate("mainWindow", "Resolution"))
        self.label_8.setText(_translate("mainWindow", "Frame rate (fps)"))
        self.label_9.setText(_translate("mainWindow", "Storage size"))
        self.label_10.setText(_translate("mainWindow", "x"))
        self.checkbox_aspect_ratio.setText(_translate("mainWindow", "keep aspect ratio"))
        self.label_11.setText(_translate("mainWindow", "Bit rate "))
        self.radiobutton_cbr.setText(_translate("mainWindow", "CBR"))
        self.radiobutton_vbr.setText(_translate("mainWindow", "VBR"))
        self.label_12.setText(_translate("mainWindow", "kbps"))
        self.label_13.setText(_translate("mainWindow", "Maximum Bit rate"))
        self.label_14.setText(_translate("mainWindow", "kbps"))
        self.pushButton_start_transcoding.setText(_translate("mainWindow", "start transcoding"))
        self.label_15.setText(_translate("mainWindow", "Content Packageing:"))
        self.pushbutton_browse_file.setText(_translate("mainWindow", "Browse..."))
        self.pushButton_start_generating_DASH_MPD.setText(_translate("mainWindow", "start generating DASH MPD"))
        self.label_17.setText(_translate("mainWindow", "Bit rate (kbps)"))
        self.radiobutton_abr.setText(_translate("mainWindow", "ABR"))
        self.label_18.setText(_translate("mainWindow", "kbps (Two-Pass)"))
        self.lineEdit_cbr.setText(_translate("mainWindow", "1000"))
        self.label_16.setText(_translate("mainWindow", "ms"))
        self.label_19.setText(_translate("mainWindow", "Segment duration"))
        self.checkBox_custom_segment_duration.setText(_translate("mainWindow", "Custom segment duration"))
        self.label_2.setText(_translate("mainWindow", "Saved as..."))
        self.lineEdit_saved_name.setText(_translate("mainWindow", "output.mp4"))
        self.label_20.setText(_translate("mainWindow", "Title"))
        self.lineEdit_dash_title.setText(_translate("mainWindow", "output"))

